// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Microsoft.Accordant
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using System.Text;

    public class StateSourceCodeGenerator
    {
        private StringBuilder builder { get; set; }
        private int indentation;

        private Assembly assembly;
        private string targetNamespace;
        private string[] arguments;

        public StateSourceCodeGenerator(
            Assembly assembly,
            string targetNamespace,
            string[] arguments = null)
        {
            this.assembly = assembly;
            this.targetNamespace = targetNamespace;
            this.arguments = arguments;
        }

        public string GenerateSourceCode()
        {
            builder = new StringBuilder();
            indentation = 0;

            EmitLine("//");
            EmitLine("// WARNING: This file is autogenerated and any changes made to it may be overwritten.");
            EmitLine($"// Generated on: {DateTime.Now.ToString()}");
            EmitLine($"// Generated by: StateSourceCodeGenerator.exe");
            if (arguments != null)
            {
                EmitLine($"// Arguments: {string.Join(" ", arguments)} ");
            }
            EmitLine("//");
            EmitLine();

            EmitLine($"namespace {targetNamespace}");
            EmitLine("{");

            using (new WithIndentation(this))
            {
                EmitLine("using global::System;");
                EmitLine("using global::System.Collections.Generic;");
                EmitLine("using global::Microsoft.Accordant;");
            }

            var processedStateDefinitionTypes = new HashSet<Type>();

            foreach (var type in assembly.GetTypes())
            {
                if (IsStateDefinitionType(type))
                {
                    using (new WithIndentation(this))
                    {
                        EmitLine();
                        GenerateSourceCodeForType(type, processedStateDefinitionTypes);
                    }
                }
            }

            EmitLine("}");

            return builder.ToString();
        }

        private void GenerateSourceCodeForType(
            Type stateDefinitionType,
            HashSet<Type> processedStateDefinitionTypes)
        {
            if (processedStateDefinitionTypes.Contains(stateDefinitionType))
            {
                return;
            }

            processedStateDefinitionTypes.Add(stateDefinitionType);

            if (!IsSupportedType(stateDefinitionType, out var path))
            {
                var pathStr = string.Join(".", path);
                throw new Exception(
                    $"Cannot generate state class for type {stateDefinitionType.Name} " +
                    $"because of type at path {pathStr}");
            }

            var baseClassName = "State";
            bool derivedStateClass = false;

            var baseType = stateDefinitionType.BaseType;
            if (baseType != null &&
                IsStateDefinitionType(baseType))
            {
                GenerateSourceCodeForType(baseType, processedStateDefinitionTypes);
                baseClassName = baseType.Name;
                derivedStateClass = true;
            }

            // Generate class declaration
            EmitLine($"public partial class {GetGeneratedPropertyTypeName(stateDefinitionType)} : {baseClassName}");
            EmitLine("{");

            using (new WithIndentation(this))
            {
                var properties = stateDefinitionType.GetProperties(
                    BindingFlags.Public |
                    BindingFlags.Instance |
                    BindingFlags.DeclaredOnly);

                // Field declarations
                foreach (var property in properties)
                {
                    string fieldName = property.Name + "FieldName";
                    EmitLine($"private string {fieldName} = \"{property.Name}\";");
                }
                EmitLine();

                if (!derivedStateClass)
                {
                    EmitLine("protected DictionaryState<State> fieldStates;");
                    EmitLine();
                }

                // Constructor
                EmitLine($"public {GetGeneratedPropertyTypeName(stateDefinitionType)}()");
                EmitLine("{");

                using (new WithIndentation(this))
                {
                    if (!derivedStateClass)
                    {
                        EmitLine("fieldStates = new DictionaryState<State>();");
                    }

                    foreach (var property in properties)
                    {
                        static string ConstructFieldStateInitializationString(PropertyInfo property)
                        {
                            if (ShouldUseAtomicState(property))
                            {
                                var atomicAttribute = property.GetCustomAttribute<AtomicAttribute>();
                                var customStringRepresentationAddition = atomicAttribute == null ?
                                    "" :
                                    ", " + atomicAttribute.ToStringMethod;

                                return $"new AtomicState<{GetGeneratedPropertyTypeName(property)}>(default{customStringRepresentationAddition})";
                            }
                            else
                            {
                                return "null";
                            }
                        }

                        var initializationString =
                            ConstructFieldStateInitializationString(property);

                        EmitLine($"fieldStates[{property.Name + "FieldName"}] = {initializationString};");
                    }

                    EmitLine();
                    EmitLine("Initialize();");
                }

                EmitLine("}");

                EmitLine();
                EmitLine("partial void Initialize();");

                // Properties
                foreach (var property in properties)
                {
                    EmitLine();

                    static string ConstructGetExpression(
                        PropertyInfo property)
                    {
                        var fieldStatesLookup = $"fieldStates[{property.Name + "FieldName"}]";

                        var generatedPropertyTypeName = GetGeneratedPropertyTypeName(property);

                        if (ShouldUseAtomicState(property))
                        {
                            return $"((AtomicState<{generatedPropertyTypeName}>){fieldStatesLookup}).Value";
                        }
                        else
                        {
                            return $"({generatedPropertyTypeName}){fieldStatesLookup}";
                        }
                    }

                    static string ConstructSetExpression(PropertyInfo property)
                    {
                        var fieldStatesLookup = $"fieldStates[{property.Name}FieldName]";

                        var generatedPropertyTypeName = GetGeneratedPropertyTypeName(property);

                        string setExpression;
                        if (ShouldUseAtomicState(property))
                        {
                            var atomicAttribute = property.GetCustomAttribute<AtomicAttribute>();
                            var customStringRepresentationAddition = atomicAttribute == null ?
                                "" :
                                ", " + atomicAttribute.ToStringMethod;

                            setExpression = $"new AtomicState<{generatedPropertyTypeName}>(value{customStringRepresentationAddition})";
                        }
                        else
                        {
                            setExpression = "value";
                        }

                        return $"{fieldStatesLookup} = {setExpression}";
                    }

                    var getExpression = ConstructGetExpression(property);
                    var setExpression = ConstructSetExpression(property);

                    EmitLine($"public {GetGeneratedPropertyTypeName(property)} {property.Name}");
                    EmitLine("{");
                    using (new WithIndentation(this))
                    {
                        EmitLine($"get => {getExpression};");
                        EmitLine($"set => {setExpression};");
                    }
                    EmitLine("}");
                }

                // Clone, ToString, LockComponents methods
                EmitLine();
                EmitLine("protected override void CloneInternal(Dictionary<object, object> clonedMap)");
                EmitLine("{");
                using (new WithIndentation(this))
                {
                    EmitLine($"var clonedObject = new {stateDefinitionType.Name}();");
                    EmitLine("clonedMap[this] = clonedObject;");
                    EmitLine("clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);");
                }
                EmitLine("}");
                EmitLine();
                EmitLine("protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)");
                EmitLine("{");
                using (new WithIndentation(this))
                {
                    EmitLine($"return nameof({stateDefinitionType.Name}) + \" \" + fieldStates.StringRepresentation(objectPaths, path);");
                }
                EmitLine("}");
                EmitLine();
                EmitLine("protected override void LockComponents(HashSet<object> visited)");
                EmitLine("{");
                using (new WithIndentation(this))
                {
                    EmitLine("fieldStates.Lock(visited);");
                }
                EmitLine("}");
                EmitLine();
            }

            EmitLine("}");
        }

        private class WithIndentation : IDisposable
        {
            private StateSourceCodeGenerator generator;
            private int originalIndentation;

            public WithIndentation(StateSourceCodeGenerator generator)
            {
                this.generator = generator;

                originalIndentation = generator.indentation;
                generator.indentation += 4;
            }

            public void Dispose()
            {
                generator.indentation = originalIndentation;
            }
        }

        private void EmitLine(string line = null)
        {
            if (string.IsNullOrEmpty(line))
            {
                builder.AppendLine(string.Empty);
                return;
            }

            for (int i = 0; i < indentation; i++)
            {
                builder.Append(" ");
            }

            builder.AppendLine(line);
        }

        private static bool ShouldUseAtomicState(PropertyInfo property)
        {
            return
                property.GetCustomAttribute<AtomicAttribute>() != null ||
                IsSupportedPrimitive(property.PropertyType, path: null);
        }

        private static bool IsStateDefinitionType(Type type)
        {
            return type.GetCustomAttribute<StateDefinitionAttribute>() != null;
        }

        private static bool IsSupportedPrimitive(Type type, List<string> path)
        {
            var underlyingType = Nullable.GetUnderlyingType(type);
            var effectiveType = underlyingType ?? type;

            return
                effectiveType == typeof(char) ||
                effectiveType == typeof(string) ||
                effectiveType == typeof(DateTime) ||
                effectiveType == typeof(char) ||
                effectiveType == typeof(bool) ||
                effectiveType == typeof(byte) ||
                effectiveType == typeof(sbyte) ||
                effectiveType == typeof(int) ||
                effectiveType == typeof(uint) ||
                effectiveType == typeof(long) ||
                effectiveType == typeof(ulong) ||
                effectiveType == typeof(short) ||
                effectiveType == typeof(ushort) ||
                effectiveType == typeof(double) ||
                effectiveType == typeof(float) ||
                effectiveType.IsEnum;
        }

        private static bool IsSupportedObject(
            Type type,
            Dictionary<Type, bool> visitedMap,
            List<string> path)
        {
            var isObject =
                type.IsClass &&
                type.GetCustomAttribute<StateDefinitionAttribute>() != null &&
                !IsSupportedPrimitive(type, path) &&
                !IsSupportedList(type, visitedMap, path) &&
                !IsSupportedDictionary(type, visitedMap, path);

            if (!isObject)
            {
                return false;
            }

            var properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance);

            foreach (var property in properties)
            {
                var propertyType = property.PropertyType;

                path.Add(property.Name);
                if (!IsSupportedType(propertyType, visitedMap, path))
                {
                    return false;
                }
                path.RemoveAt(path.Count - 1);
            }

            return true;
        }

        private static bool IsSupportedList(
            Type type,
            Dictionary<Type, bool> visitedMap,
            List<string> path)
        {
            if (!type.IsGenericType ||
                type.GetGenericTypeDefinition() != typeof(List<>))
            {
                return false;
            }

            var elementType = type.GetGenericArguments()[0];

            path.Add("ElementType");
            var result = IsSupportedType(elementType, visitedMap, path);
            if (!result)
            {
                return false;
            }
            path.RemoveAt(path.Count - 1);

            return true;
        }

        private static bool IsSupportedDictionary(
            Type type,
            Dictionary<Type, bool> visitedMap,
            List<string> path)
        {
            if (!type.IsGenericType ||
                type.GetGenericTypeDefinition() != typeof(Dictionary<,>))
            {
                return false;
            }

            var genericArguments = type.GetGenericArguments();

            var keyType = genericArguments[0];
            var valueType = genericArguments[1];

            if (keyType != typeof(string))
            {
                path.Add("Key");
                return false;
            }

            path.Add("Value");
            var result = IsSupportedType(valueType, visitedMap, path);
            if (!result)
            {
                return false;
            }
            path.RemoveAt(path.Count - 1);

            return true;
        }

        private static bool IsSupportedType(Type type, out List<string> path)
        {
            path = new List<string>() { "$" };

            return IsSupportedType(
                type,
                visitedMap: new Dictionary<Type, bool>(),
                path);
        }

        private static bool IsSupportedType(
            Type type,
            Dictionary<Type, bool> visitedMap,
            List<string> path)
        {
            if (visitedMap.ContainsKey(type))
            {
                return visitedMap[type];
            }

            // Temporarily assuming that this type is supported in case a
            // a recursive field wants to know whether it is supported.
            visitedMap[type] = true;

            var result = IsSupportedPrimitive(type, path) ||
                IsSupportedObject(type, visitedMap, path) ||
                IsSupportedList(type, visitedMap, path) ||
                IsSupportedDictionary(type, visitedMap, path);

            visitedMap[type] = result;

            return result;
        }

        private static string GetGeneratedPropertyTypeName(PropertyInfo property)
        {
            var atomicAttribute = property.GetCustomAttribute<AtomicAttribute>();

            return atomicAttribute == null ?
                GetGeneratedPropertyTypeName(property.PropertyType) :
                GetTypeName(property.PropertyType);
        }

        private static string GetGeneratedPropertyTypeName(Type type)
        {
            if (IsSupportedList(
                type,
                visitedMap: new Dictionary<Type, bool>(),
                path: new List<string>()))
            {
                var elementType = type.GetGenericArguments()[0];

                if (IsSupportedPrimitive(
                    elementType,
                    path: null))
                {
                    return $"ListAtomicState<{GetGeneratedPropertyTypeName(elementType)}>";
                }
                else
                {
                    return $"ListState<{GetGeneratedPropertyTypeName(elementType)}>";
                }
            }
            else if (IsSupportedDictionary(
                type,
                visitedMap: new Dictionary<Type, bool>(),
                path: new List<string>()))
            {
                var valueType = type.GetGenericArguments()[1];

                if (IsSupportedPrimitive(
                    valueType,
                    path: null))
                {
                    return $"DictionaryAtomicState<{GetGeneratedPropertyTypeName(valueType)}>";
                }
                else
                {
                    return $"DictionaryState<{GetGeneratedPropertyTypeName(valueType)}>";
                }
            }
            else
            {
                return GetTypeName(type);
            }
        }

        public static string GetTypeName(Type type)
        {
            if (type.IsGenericType)
            {
                return
                    type.Name.Substring(0, type.Name.IndexOf("`")) +
                    "<" +
                    string.Join(", ", type.GetGenericArguments().Select(GetTypeName)) +
                    ">";
            }
            else
            {
                var underlyingType = Nullable.GetUnderlyingType(type);

                return underlyingType != null ?
                    underlyingType.Name + "?" :
                    type.Name;
            }
        }
    }
}
