<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="Library\ConsumerLibrary.csproj" />
    <ProjectReference Include="SharedFrameworkLibrary\SharedFrameworkLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Library\**\*.cs" />
    <Compile Remove="SharedFrameworkLibrary\**\*.cs" />
  </ItemGroup>

</Project>
