// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//
// WARNING: This file is autogenerated and any changes made to it may be overwritten.
// Generated on: 6/25/2024 11:41:09 AM
// Generated by: StateSourceCodeGenerator.exe
// Arguments: -i ..\..\Samples\StateSamples\bin\Debug\net6.0\StateSamples.dll -n StateSamples -o ..\..\Samples\StateSamples\State.g.cs 
//

namespace StateSamples
{
    using global::System;
    using global::System.Collections.Generic;
    using global::Microsoft.Accordant;

    public partial class AddressState : State
    {
        private string Line1FieldName = "Line1";
        private string Line2FieldName = "Line2";
        private string CityFieldName = "City";
        private string StateFieldName = "State";

        protected DictionaryState<State> fieldStates;

        public AddressState()
        {
            fieldStates = new DictionaryState<State>();
            fieldStates[Line1FieldName] = new AtomicState<String>(default, null);
            fieldStates[Line2FieldName] = new AtomicState<String>(default, null);
            fieldStates[CityFieldName] = new AtomicState<String>(default, null);
            fieldStates[StateFieldName] = new AtomicState<String>(default, null);

            Initialize();
        }

        partial void Initialize();

        public String Line1
        {
            get => ((AtomicState<String>)fieldStates[Line1FieldName]).Value;
            set => fieldStates[Line1FieldName] = new AtomicState<String>(value);
        }

        public String Line2
        {
            get => ((AtomicState<String>)fieldStates[Line2FieldName]).Value;
            set => fieldStates[Line2FieldName] = new AtomicState<String>(value);
        }

        public String City
        {
            get => ((AtomicState<String>)fieldStates[CityFieldName]).Value;
            set => fieldStates[CityFieldName] = new AtomicState<String>(value);
        }

        public String State
        {
            get => ((AtomicState<String>)fieldStates[StateFieldName]).Value;
            set => fieldStates[StateFieldName] = new AtomicState<String>(value);
        }

        protected override void CloneInternal(Dictionary<object, object> clonedMap)
        {
            var clonedObject = new AddressState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(AddressState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }

    public partial class PersonState : State
    {
        private string NameFieldName = "Name";
        private string AgeFieldName = "Age";
        private string AddressFieldName = "Address";

        protected DictionaryState<State> fieldStates;

        public PersonState()
        {
            fieldStates = new DictionaryState<State>();
            fieldStates[NameFieldName] = new AtomicState<String>(default, null);
            fieldStates[AgeFieldName] = new AtomicState<Int32>(default, null);
            fieldStates[AddressFieldName] = null;

            Initialize();
        }

        partial void Initialize();

        public String Name
        {
            get => ((AtomicState<String>)fieldStates[NameFieldName]).Value;
            set => fieldStates[NameFieldName] = new AtomicState<String>(value);
        }

        public Int32 Age
        {
            get => ((AtomicState<Int32>)fieldStates[AgeFieldName]).Value;
            set => fieldStates[AgeFieldName] = new AtomicState<Int32>(value);
        }

        public AddressState Address
        {
            get => (AddressState)fieldStates[AddressFieldName];
            set => fieldStates[AddressFieldName] = value;
        }

        protected override void CloneInternal(Dictionary<object, object> clonedMap)
        {
            var clonedObject = new PersonState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(PersonState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }

    public partial class CompanyState : State
    {
        private string NameFieldName = "Name";
        private string EmployeesFieldName = "Employees";

        protected DictionaryState<State> fieldStates;

        public CompanyState()
        {
            fieldStates = new DictionaryState<State>();
            fieldStates[NameFieldName] = new AtomicState<String>(default, null);
            fieldStates[EmployeesFieldName] = null;

            Initialize();
        }

        partial void Initialize();

        public String Name
        {
            get => ((AtomicState<String>)fieldStates[NameFieldName]).Value;
            set => fieldStates[NameFieldName] = new AtomicState<String>(value);
        }

        public ListState<PersonState> Employees
        {
            get => (ListState<PersonState>)fieldStates[EmployeesFieldName];
            set => fieldStates[EmployeesFieldName] = value;
        }

        protected override void CloneInternal(Dictionary<object, object> clonedMap)
        {
            var clonedObject = new CompanyState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(CompanyState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }

    public partial class AccountState : State
    {
        private string NameFieldName = "Name";
        private string TagsFieldName = "Tags";
        private string ImagesFieldName = "Images";
        private string CustomerPropertiesFieldName = "CustomerProperties";

        protected DictionaryState<State> fieldStates;

        public AccountState()
        {
            fieldStates = new DictionaryState<State>();
            fieldStates[NameFieldName] = new AtomicState<String>(default, null);
            fieldStates[TagsFieldName] = null;
            fieldStates[ImagesFieldName] = null;
            fieldStates[CustomerPropertiesFieldName] = null;

            Initialize();
        }

        partial void Initialize();

        public String Name
        {
            get => ((AtomicState<String>)fieldStates[NameFieldName]).Value;
            set => fieldStates[NameFieldName] = new AtomicState<String>(value);
        }

        public ListAtomicState<String> Tags
        {
            get => (ListAtomicState<String>)fieldStates[TagsFieldName];
            set => fieldStates[TagsFieldName] = value;
        }

        public DictionaryState<ImageState> Images
        {
            get => (DictionaryState<ImageState>)fieldStates[ImagesFieldName];
            set => fieldStates[ImagesFieldName] = value;
        }

        public DictionaryAtomicState<String> CustomerProperties
        {
            get => (DictionaryAtomicState<String>)fieldStates[CustomerPropertiesFieldName];
            set => fieldStates[CustomerPropertiesFieldName] = value;
        }

        protected override void CloneInternal(Dictionary<object, object> clonedMap)
        {
            var clonedObject = new AccountState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(AccountState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }

    public partial class ImageState : State
    {
        private string NameFieldName = "Name";
        private string ContentTypeFieldName = "ContentType";
        private string ContentFieldName = "Content";

        protected DictionaryState<State> fieldStates;

        public ImageState()
        {
            fieldStates = new DictionaryState<State>();
            fieldStates[NameFieldName] = new AtomicState<String>(default, null);
            fieldStates[ContentTypeFieldName] = new AtomicState<String>(default, null);
            fieldStates[ContentFieldName] = new AtomicState<List<Byte>>(default, StateSamples.StateDefinition.ImageState.ContentToString);

            Initialize();
        }

        partial void Initialize();

        public String Name
        {
            get => ((AtomicState<String>)fieldStates[NameFieldName]).Value;
            set => fieldStates[NameFieldName] = new AtomicState<String>(value);
        }

        public String ContentType
        {
            get => ((AtomicState<String>)fieldStates[ContentTypeFieldName]).Value;
            set => fieldStates[ContentTypeFieldName] = new AtomicState<String>(value);
        }

        public List<Byte> Content
        {
            get => ((AtomicState<List<Byte>>)fieldStates[ContentFieldName]).Value;
            set => fieldStates[ContentFieldName] = new AtomicState<List<Byte>>(value);
        }

        protected override void CloneInternal(Dictionary<object, object> clonedMap)
        {
            var clonedObject = new ImageState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(ImageState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }

    public partial class VehicleState : State
    {
        private string MakeFieldName = "Make";
        private string ModelFieldName = "Model";
        private string YearFieldName = "Year";

        protected DictionaryState<State> fieldStates;

        public VehicleState()
        {
            fieldStates = new DictionaryState<State>();
            fieldStates[MakeFieldName] = new AtomicState<String>(default, null);
            fieldStates[ModelFieldName] = new AtomicState<String>(default, null);
            fieldStates[YearFieldName] = new AtomicState<DateTime>(default, null);

            Initialize();
        }

        partial void Initialize();

        public String Make
        {
            get => ((AtomicState<String>)fieldStates[MakeFieldName]).Value;
            set => fieldStates[MakeFieldName] = new AtomicState<String>(value);
        }

        public String Model
        {
            get => ((AtomicState<String>)fieldStates[ModelFieldName]).Value;
            set => fieldStates[ModelFieldName] = new AtomicState<String>(value);
        }

        public DateTime Year
        {
            get => ((AtomicState<DateTime>)fieldStates[YearFieldName]).Value;
            set => fieldStates[YearFieldName] = new AtomicState<DateTime>(value);
        }

        protected override void CloneInternal(Dictionary<object, object> clonedMap)
        {
            var clonedObject = new VehicleState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(VehicleState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }

    public partial class CarState : VehicleState
    {
        private string TrunkSizeFieldName = "TrunkSize";

        public CarState()
        {
            fieldStates[TrunkSizeFieldName] = new AtomicState<Int32>(default, null);

            Initialize();
        }

        partial void Initialize();

        public Int32 TrunkSize
        {
            get => ((AtomicState<Int32>)fieldStates[TrunkSizeFieldName]).Value;
            set => fieldStates[TrunkSizeFieldName] = new AtomicState<Int32>(value);
        }

        protected override void CloneInternal(Dictionary<object, object> clonedMap)
        {
            var clonedObject = new CarState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(CarState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }

    public partial class MotorcycleState : VehicleState
    {
        private string HasSideCarFieldName = "HasSideCar";

        public MotorcycleState()
        {
            fieldStates[HasSideCarFieldName] = new AtomicState<Boolean>(default, null);

            Initialize();
        }

        partial void Initialize();

        public Boolean HasSideCar
        {
            get => ((AtomicState<Boolean>)fieldStates[HasSideCarFieldName]).Value;
            set => fieldStates[HasSideCarFieldName] = new AtomicState<Boolean>(value);
        }

        protected override void CloneInternal(Dictionary<object, object> clonedMap)
        {
            var clonedObject = new MotorcycleState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(MotorcycleState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }
}
