// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Microsoft.Accordant.Examples.Http;

using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.Accordant;
using NUnit.Framework;

/// <summary>
/// Example test that demonstrates testing an HTTP API with Accordant.
/// Uses the ApiResult pattern for clean response handling.
/// </summary>
public class UserApiTests
{
    private HttpClient _httpClient;
    private UserApiSpec _spec;
    private TestingContext _context;

    [SetUp]
    public void Setup()
    {
        // In a real test, you'd create a test server:
        // using var factory = new WebApplicationFactory<Program>();
        // _httpClient = factory.CreateClient();
        
        _spec = new UserApiSpec();
        _context = _spec.CreateTestingContext();
    }

    [Test]
    public async Task AutoGeneratedTests_UserCrud()
    {
        // 1. Define inputs - all the operations to test
        var inputs = new InputSet
        {
            _spec.CreateUser.With(new CreateUserRequest 
            { 
                UserId = "alice", 
                Name = "Alice", 
                Email = "alice@example.com" 
            }, "Create Alice"),
            
            _spec.CreateUser.With(new CreateUserRequest 
            { 
                UserId = "bob", 
                Name = "Bob", 
                Email = "bob@example.com" 
            }, "Create Bob"),
            
            // Test invalid input
            _spec.CreateUser.With(new CreateUserRequest 
            { 
                UserId = "invalid", 
                Name = "Invalid", 
                Email = ""  // Empty email - should fail validation
            }, "Create with invalid email"),
            
            _spec.GetUser.With("alice", "Get Alice"),
            _spec.GetUser.With("unknown", "Get unknown user"),
            
            _spec.DeleteUser.With("alice", "Delete Alice"),
        };

        // 2. Generate test cases
        var testCases = _spec.GenerateTests(
            new UserApiState(),
            inputs,
            new TestGenerationOptions
            {
                // Limit exploration
                StateConstraint = s => ((UserApiState)s).Users.Count < 3,
                MaxDepth = 4
            });

        // 3. Run tests
        _context.Register(new UserApiClient(_httpClient));

        var results = await _spec.RunTests(
            _context,
            new UserApiState(),
            testCases,
            new TestExecutionOptions
            {
                // Reset before each test
                BeforeEachAsync = async info =>
                {
                    // In a real test: await ResetDatabaseAsync();
                    info.Context.Register(new UserApiClient(_httpClient));
                    await Task.CompletedTask;
                },
                
                // Log failures for debugging
                AfterEach = info =>
                {
                    if (!info.Success)
                        TestContext.WriteLine($"FAILED: {info.FailureMessage}");
                }
            });

        // 4. Assert all passed
        Assert.IsTrue(
            results.All(r => r.Success),
            $"Failed tests: {string.Join(", ", results.Where(r => !r.Success).Select(r => r.LastFailureMessage))}");
    }

    [Test]
    public async Task ManualTest_CreateAndGetUser()
    {
        _context.Register(new UserApiClient(_httpClient));
        var stateProfile = new StateProfile(new UserApiState());

        // Helper for manual testing
        async Task<TResp> Allows<TReq, TResp>(
            Operation<TReq, TResp, UserApiState> op, TReq request)
        {
            var response = await op.ExecuteAsync(_context, request);
            var (isValid, message, nextProfile) = _spec.Allows(op, request, response, stateProfile);
            Assert.IsTrue(isValid, message);
            stateProfile = nextProfile;
            return response;
        }

        // Execute scenario
        var createResult = await Allows(_spec.CreateUser, new CreateUserRequest
        {
            UserId = "alice",
            Name = "Alice",
            Email = "alice@example.com"
        });
        Assert.IsTrue(createResult.IsSuccess);
        Assert.AreEqual("alice", createResult.Data?.Id);

        var getResult = await Allows(_spec.GetUser, "alice");
        Assert.IsTrue(getResult.IsSuccess);
        Assert.AreEqual("Alice", getResult.Data?.Name);

        // Try to create duplicate - should conflict
        var duplicateResult = await Allows(_spec.CreateUser, new CreateUserRequest
        {
            UserId = "alice",
            Name = "Alice Again",
            Email = "alice2@example.com"
        });
        Assert.IsTrue(duplicateResult.IsConflict);
    }
}
