// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Microsoft.Accordant.SourceGenerator;

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

public partial class StateSourceGenerator
{
    /// <summary>
    /// C# keywords that must be escaped with @ when used as identifiers.
    /// Source: ECMA-334 (C# Language Specification), Section 7.4.4 "Keywords".
    /// See also: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/
    /// </summary>
    private static readonly HashSet<string> CSharpKeywords = new HashSet<string>
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while"
    };

    /// <summary>
    /// Escapes a C# identifier if it's a keyword by prefixing with @.
    /// </summary>
    private static string EscapeIdentifier(string identifier)
    {
        return CSharpKeywords.Contains(identifier) ? "@" + identifier : identifier;
    }

    private static string GenerateStateClass(StateClassInfo classInfo)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.IO.Hashing;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine();

        if (classInfo.Namespace != null)
        {
            sb.AppendLine($"namespace {classInfo.Namespace}");
            sb.AppendLine("{");
        }

        var indent = classInfo.Namespace != null ? "    " : "";

        // Nested types are no longer supported (STATE007)
        // Generate the class directly at namespace level

        var accessibility = classInfo.Modifiers.IsPublic ? "public" : "internal";
        var typeKeyword = classInfo.Modifiers.IsRecord ? "record" : "class";

        // Build class name with generic type parameters
        var classNameWithGenerics = classInfo.ClassName;
        if (classInfo.TypeParameters.Length > 0)
        {
            classNameWithGenerics += "<" + string.Join(", ", classInfo.TypeParameters.Select(tp => tp.Name)) + ">";
        }

        // Build inheritance clause - only add : State if not already inheriting
        var inheritanceClause = classInfo.Inheritance.InheritsFromState ? "" : " : global::Microsoft.Accordant.State";

        sb.Append($"{indent}{accessibility} partial {typeKeyword} {classNameWithGenerics}{inheritanceClause}");

        // Add generic type constraints
        if (classInfo.TypeParameters.Length > 0)
        {
            sb.AppendLine();
            foreach (var typeParam in classInfo.TypeParameters)
            {
                if (typeParam.Constraints.Length > 0)
                {
                    sb.AppendLine($"{indent}    where {typeParam.Name} : {string.Join(", ", typeParam.Constraints)}");
                }
            }
        }
        else
        {
            sb.AppendLine();
        }

        sb.AppendLine($"{indent}{{");

        // Generate CloneInternal
        GenerateCloneInternal(sb, classInfo, indent + "    ");

        sb.AppendLine();

        // Generate StringRepresentationInternal
        GenerateStringRepresentationInternal(sb, classInfo, indent + "    ");

        sb.AppendLine();

        // Generate AppendFieldHashes for efficient incremental hashing
        GenerateAppendFieldHashes(sb, classInfo, indent + "    ");

        sb.AppendLine();

        // Generate FreezeComponents
        GenerateFreezeComponents(sb, classInfo, indent + "    ");

        sb.AppendLine($"{indent}}}");

        if (classInfo.Namespace != null)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void GenerateCloneInternal(
        StringBuilder sb,
        StateClassInfo classInfo,
        string indent)
    {
        // Build class name with generics for constructor
        var classNameWithGenerics = classInfo.ClassName;
        if (classInfo.TypeParameters.Length > 0)
        {
            classNameWithGenerics += "<" + string.Join(", ", classInfo.TypeParameters.Select(tp => tp.Name)) + ">";
        }

        // Generate factory method for creating the correct clone type
        // Use 'override' if there's a [State] base (covariant return type), otherwise 'virtual'
        var factoryModifier = classInfo.Inheritance.HasImmediateStateBase ? "override" : "virtual";
        sb.AppendLine($"{indent}protected {factoryModifier} {classNameWithGenerics} CreateCloneInstance() => new {classNameWithGenerics}();");
        sb.AppendLine();

        sb.AppendLine($"{indent}protected override void CloneInternal(Dictionary<object, object> clonedMap)");
        sb.AppendLine($"{indent}{{");

        if (classInfo.Inheritance.HasImmediateStateBase)
        {
            // Call base to handle inherited properties, then handle own properties
            sb.AppendLine($"{indent}    base.CloneInternal(clonedMap);");
            sb.AppendLine($"{indent}    var clone = ({classNameWithGenerics})clonedMap[this];");
        }
        else
        {
            // No [State] base - create instance and register
            sb.AppendLine($"{indent}    var clone = CreateCloneInstance();");
            sb.AppendLine($"{indent}    clonedMap[this] = clone;");
        }

        if (classInfo.OwnProperties.Length > 0)
        {
            sb.AppendLine();
            foreach (var prop in classInfo.OwnProperties)
            {
                GeneratePropertyClone(sb, prop, indent + "    ");
            }
        }

        sb.AppendLine($"{indent}}}");
    }

    private static void GeneratePropertyClone(
        StringBuilder sb,
        PropertyInfo prop,
        string indent)
    {
        var cloneName = "clone";
        var thisName = "this";
        var escapedName = EscapeIdentifier(prop.Name);

        // [SharedState] properties are copied by reference (not deep cloned)
        if (prop.SharedState.IsShared)
        {
            sb.AppendLine($"{indent}{cloneName}.{escapedName} = {thisName}.{escapedName};");
            return;
        }

        var cloneExpr = GenerateCloneExpression(prop.TypeInfo, $"{thisName}.{escapedName}", "clonedMap");
        sb.AppendLine($"{indent}{cloneName}.{escapedName} = {cloneExpr};");
    }

    private static string GenerateCloneExpression(TypeInfo typeInfo, string valueExpr, string mapName)
        => TypeKindDispatch.Clone(typeInfo, valueExpr, mapName);

    private static void GenerateStringRepresentationInternal(
        StringBuilder sb,
        StateClassInfo classInfo,
        string indent)
    {
        sb.AppendLine($"{indent}protected override string StringRepresentationInternal(");
        sb.AppendLine($"{indent}    Dictionary<object, string> objectPaths,");
        sb.AppendLine($"{indent}    string path,");
        sb.AppendLine($"{indent}    bool forceRecompute)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var sb = new StringBuilder();");
        // Use stable type name that doesn't include assembly-qualified generic type arguments,
        // ensuring fingerprints remain stable across assembly versions.
        sb.AppendLine($"{indent}    sb.Append(global::Microsoft.Accordant.State.GetStableTypeName(GetType()) + \" {{\");");

        var first = true;
        foreach (var prop in classInfo.Properties)
        {
            var separator = first ? "" : ", ";
            first = false;

            GeneratePropertyFingerprint(sb, prop, indent + "    ", separator);
        }

        sb.AppendLine($"{indent}    sb.Append(\"}}\");");
        sb.AppendLine($"{indent}    return sb.ToString();");
        sb.AppendLine($"{indent}}}");
    }

    /// <summary>
    /// Generates the ComputeHashCore override for efficient incremental hashing.
    /// This avoids string allocation by computing the hash directly from field values.
    /// The cycle check is handled by AppendHashCore in the base class.
    /// </summary>
    private static void GenerateAppendFieldHashes(
        StringBuilder sb,
        StateClassInfo classInfo,
        string indent)
    {
        sb.AppendLine($"{indent}protected override void AppendFieldHashes(XxHash64 hasher, Dictionary<object, int> visited)");
        sb.AppendLine($"{indent}{{");

        // Include stable type name in hash for type differentiation
        sb.AppendLine($"{indent}    global::Microsoft.Accordant.State.AppendLengthPrefixedString(hasher, global::Microsoft.Accordant.State.GetStableTypeName(GetType()));");
        sb.AppendLine();

        foreach (var prop in classInfo.Properties)
        {
            GeneratePropertyHash(sb, prop, indent + "    ");
        }

        sb.AppendLine($"{indent}}}");
    }

    /// <summary>
    /// Generates the hash computation for a single property.
    /// </summary>
    private static void GeneratePropertyHash(
        StringBuilder sb,
        PropertyInfo prop,
        string indent)
    {
        var escapedName = EscapeIdentifier(prop.Name);
        var valueExpr = $"this.{escapedName}";

        // Include property name in hash for field ordering differentiation
        sb.AppendLine($"{indent}global::Microsoft.Accordant.State.AppendLengthPrefixedString(hasher, \"{prop.Name}\");");

        // [SharedState] properties use custom fingerprint method or default State hash
        if (prop.SharedState.IsShared)
        {
            GenerateSharedStateHash(sb, prop, indent, escapedName);
            return;
        }

        GenerateHashExpression(sb, prop.TypeInfo, valueExpr, indent);
    }

    /// <summary>
    /// Generates hash code for a [SharedState] property.
    /// </summary>
    private static void GenerateSharedStateHash(
        StringBuilder sb,
        PropertyInfo prop,
        string indent,
        string escapedName)
    {
        var valueExpr = $"this.{escapedName}";

        if (prop.SharedState.FingerprintMemberName != null)
        {
            // Custom fingerprint specified - hash the fingerprint string
            // Use method call syntax if it's a method, property access if it's a property
            var fingerprintExpr = prop.SharedState.FingerprintIsMethod
                ? $"this.{prop.SharedState.FingerprintMemberName}({valueExpr})"
                : $"this.{prop.SharedState.FingerprintMemberName}";
            sb.AppendLine($"{indent}var _{escapedName}Fp = {fingerprintExpr};");
            TypeKindHandler.StartNullCheckedHash(sb, indent, $"_{escapedName}Fp != null");
            sb.AppendLine($"{indent}    global::Microsoft.Accordant.State.AppendLengthPrefixedString(hasher, _{escapedName}Fp);");
            TypeKindHandler.EndNullCheckedHash(sb, indent);
        }
        else
        {
            // State type - use AppendHashCore
            GenerateHashExpression(sb, prop.TypeInfo, valueExpr, indent);
        }
    }

    /// <summary>
    /// Delegates to TypeKindDispatch for type-specific hash generation.
    /// </summary>
    private static void GenerateHashExpression(
        StringBuilder sb,
        TypeInfo typeInfo,
        string valueExpr,
        string indent,
        int depth = 0)
        => TypeKindDispatch.Hash(sb, typeInfo, valueExpr, indent, depth);

    private static void GeneratePropertyFingerprint(
        StringBuilder sb,
        PropertyInfo prop,
        string indent,
        string separator)
    {
        var escapedName = EscapeIdentifier(prop.Name);
        // Use unescaped name in the fingerprint string (prop.Name), but escaped in code (escapedName)
        sb.AppendLine($"{indent}sb.Append(\"{separator}{prop.Name}=\");");

        // [SharedState] properties use custom fingerprint method or default State fingerprint
        if (prop.SharedState.IsShared)
        {
            GenerateSharedStateFingerprint(sb, prop, indent, escapedName);
            return;
        }

        var fpExpr = GenerateFingerprintExpression(prop.TypeInfo, $"this.{escapedName}", "objectPaths", $"path + \".{prop.Name}\"");
        sb.AppendLine($"{indent}sb.Append({fpExpr});");
    }

    private static void GenerateSharedStateFingerprint(
        StringBuilder sb,
        PropertyInfo prop,
        string indent,
        string escapedName)
    {
        var valueExpr = $"this.{escapedName}";

        if (prop.SharedState.FingerprintMemberName != null)
        {
            // Custom fingerprint specified
            // Use method call syntax if it's a method, property access if it's a property
            // The fingerprint property/method handles null internally
            var fingerprintExpr = prop.SharedState.FingerprintIsMethod
                ? $"this.{prop.SharedState.FingerprintMemberName}({valueExpr})"
                : $"this.{prop.SharedState.FingerprintMemberName}";
            sb.AppendLine($"{indent}sb.Append({fingerprintExpr} ?? \"null\");");
        }
        else
        {
            // No custom fingerprint - must be a State type (validated at extraction)
            // Use the State's StringRepresentation
            var fpExpr = GenerateFingerprintExpression(prop.TypeInfo, valueExpr, "objectPaths", $"path + \".{prop.Name}\"");
            sb.AppendLine($"{indent}sb.Append({fpExpr});");
        }
    }

    private static string GenerateFingerprintExpression(
        TypeInfo typeInfo,
        string valueExpr,
        string pathsName,
        string pathExpr)
        => TypeKindDispatch.Fingerprint(typeInfo, valueExpr, pathsName, pathExpr);

    private static void GenerateFreezeComponents(
        StringBuilder sb,
        StateClassInfo classInfo,
        string indent)
    {
        sb.AppendLine($"{indent}protected override void FreezeComponents(HashSet<object> visited)");
        sb.AppendLine($"{indent}{{");

        foreach (var prop in classInfo.Properties)
        {
            GeneratePropertyFreeze(sb, prop, indent + "    ");
        }

        sb.AppendLine($"{indent}}}");
    }

    private static void GeneratePropertyFreeze(StringBuilder sb, PropertyInfo prop, string indent)
    {
        // [SharedState] properties are not frozen (they're external/immutable)
        if (prop.SharedState.IsShared)
        {
            return;
        }

        var escapedName = EscapeIdentifier(prop.Name);
        TypeKindDispatch.Freeze(sb, prop.TypeInfo, $"this.{escapedName}", indent, 0);
    }
}
