<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Specmine.Accordant\Specmine.Accordant.csproj" />
    <ProjectReference Include="..\..\src\Specmine\Specmine.csproj" />
    <ProjectReference Include="..\..\..\..\Accordant.Operations\Accordant.Operations.csproj" />
    <ProjectReference Include="..\..\..\..\Accordant.SourceGenerator\Accordant.SourceGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
