<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NuspecFile>Microsoft.Accordant.nuspec</NuspecFile>
    <NoPackageAnalysis>true</NoPackageAnalysis>
  </PropertyGroup>

</Project>
