// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Stack
{
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.Accordant;
    using NUnit.Framework;

    public class Tests
    {
        public static StackSpec Spec { get; } = new StackSpec();

        [Test]
        public static void BasicTests()
        {
            var stack = new Stack<int>();

            stack.Push(1);
            stack.Push(2);

            Assert.IsTrue(stack.Count() == 2);
        }

        [Test]
        public static async Task AutoGeneratedSequentialTests()
        {
            var inputs = new InputSet()
            {
                Spec.Push.With(1, "Push 1"),
                Spec.Push.With(2, "Push 2"),
                Spec.Pop.With("Pop"),
                Spec.Peek.With("Peek"),
                Spec.IsEmpty.With("IsEmpty"),
                Spec.Count.With("Count")
            };

            var testGenerationOptions = new TestGenerationOptions()
            {
                StateConstraint = (s) =>
                {
                    var stackState = (StackState<int>)s;

                    var distinctCount = stackState.Items.Distinct().Count();

                    return
                        stackState.Items.Count < 3 &&
                        distinctCount == stackState.Items.Count;
                }
            };

            var initialState = new StackState<int>();
            var testCases = Spec.GenerateTests(
                initialState,
                inputs,
                testGenerationOptions);

            var context = Spec.CreateTestingContext();

            var results = await Spec.RunTests(
                context,
                initialState,
                testCases,
                new TestExecutionOptions
                {
                    BeforeEach = _ => context.Register(new Stack<int>())
                });

            Assert.IsTrue(
                results.All(r => r.Success),
                "Some test cases failed");
        }

        [Test]
        public static async Task AutoGeneratedConcurrentTests()
        {
            var inputs = new InputSet()
            {
                Spec.Push.With(1, "Push 1"),
                Spec.Push.With(2, "Push 2"),
                Spec.Pop.With("Pop"),
                Spec.Peek.With("Peek"),
                Spec.IsEmpty.With("IsEmpty"),
                Spec.Count.With("Count")
            };

            var testGenerationOptions = new TestGenerationOptions()
            {
                StateConstraint = (s) =>
                {
                    var stackState = (StackState<int>)s;

                    var distinctCount = stackState.Items.Distinct().Count();

                    return
                        stackState.Items.Count < 3 &&
                        distinctCount == stackState.Items.Count;
                }
            };

            var initialState = new StackState<int>();
            var testCases = Spec.GenerateConcurrentTests(
                initialState,
                inputs,
                testGenerationOptions);

            var context = Spec.CreateTestingContext();

            var results = await Spec.RunTests(
                context,
                initialState,
                testCases,
                new TestExecutionOptions
                {
                    BeforeEach = _ => context.Register(new Stack<int>())
                });

            Assert.IsTrue(
                results.All(r => r.Success),
                "Some test cases failed.");
        }
    }
}
