// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//
// WARNING: This file is autogenerated and any changes made to it may be overwritten.
// Generated on: 6/25/2024 11:40:48 AM
// Generated by: StateSourceCodeGenerator.exe
// Arguments: -i ..\..\Samples\TerminationDetection\bin\Debug\net6.0\TerminationDetection.dll -n TerminationDetection -o ..\..\Samples\TerminationDetection\State\EWD998State.g.cs 
//

namespace TerminationDetection
{
    using global::System;
    using global::System.Collections.Generic;
    using global::Microsoft.Accordant;

    public partial class TokenState : State
    {
        private string NodeIndexFieldName = "NodeIndex";
        private string QFieldName = "Q";
        private string ColorFieldName = "Color";

        protected DictionaryState<State> fieldStates;

        public TokenState()
        {
            fieldStates = new DictionaryState<State>();
            fieldStates[NodeIndexFieldName] = new AtomicState<Int32>(default, null);
            fieldStates[QFieldName] = new AtomicState<Int32>(default, null);
            fieldStates[ColorFieldName] = new AtomicState<Color>(default, null);

            Initialize();
        }

        partial void Initialize();

        public Int32 NodeIndex
        {
            get => ((AtomicState<Int32>)fieldStates[NodeIndexFieldName]).Value;
            set => fieldStates[NodeIndexFieldName] = new AtomicState<Int32>(value);
        }

        public Int32 Q
        {
            get => ((AtomicState<Int32>)fieldStates[QFieldName]).Value;
            set => fieldStates[QFieldName] = new AtomicState<Int32>(value);
        }

        public Color Color
        {
            get => ((AtomicState<Color>)fieldStates[ColorFieldName]).Value;
            set => fieldStates[ColorFieldName] = new AtomicState<Color>(value);
        }

        protected override void CloneInternal(Dictionary<object, object> clonedMap)
        {
            var clonedObject = new TokenState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(TokenState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }

    public partial class NodeState : State
    {
        private string ActiveFieldName = "Active";
        private string ColorFieldName = "Color";
        private string PendingFieldName = "Pending";
        private string CounterFieldName = "Counter";

        protected DictionaryState<State> fieldStates;

        public NodeState()
        {
            fieldStates = new DictionaryState<State>();
            fieldStates[ActiveFieldName] = new AtomicState<Boolean>(default, null);
            fieldStates[ColorFieldName] = new AtomicState<Color>(default, null);
            fieldStates[PendingFieldName] = new AtomicState<Int32>(default, null);
            fieldStates[CounterFieldName] = new AtomicState<Int32>(default, null);

            Initialize();
        }

        partial void Initialize();

        public Boolean Active
        {
            get => ((AtomicState<Boolean>)fieldStates[ActiveFieldName]).Value;
            set => fieldStates[ActiveFieldName] = new AtomicState<Boolean>(value);
        }

        public Color Color
        {
            get => ((AtomicState<Color>)fieldStates[ColorFieldName]).Value;
            set => fieldStates[ColorFieldName] = new AtomicState<Color>(value);
        }

        public Int32 Pending
        {
            get => ((AtomicState<Int32>)fieldStates[PendingFieldName]).Value;
            set => fieldStates[PendingFieldName] = new AtomicState<Int32>(value);
        }

        public Int32 Counter
        {
            get => ((AtomicState<Int32>)fieldStates[CounterFieldName]).Value;
            set => fieldStates[CounterFieldName] = new AtomicState<Int32>(value);
        }

        protected override void CloneInternal(Dictionary<object, object> clonedMap)
        {
            var clonedObject = new NodeState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(NodeState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }

    public partial class SystemState : State
    {
        private string NodesFieldName = "Nodes";
        private string TokenFieldName = "Token";

        protected DictionaryState<State> fieldStates;

        public SystemState()
        {
            fieldStates = new DictionaryState<State>();
            fieldStates[NodesFieldName] = null;
            fieldStates[TokenFieldName] = null;

            Initialize();
        }

        partial void Initialize();

        public ListState<NodeState> Nodes
        {
            get => (ListState<NodeState>)fieldStates[NodesFieldName];
            set => fieldStates[NodesFieldName] = value;
        }

        public TokenState Token
        {
            get => (TokenState)fieldStates[TokenFieldName];
            set => fieldStates[TokenFieldName] = value;
        }

        protected override void CloneInternal(Dictionary<object, object> clonedMap)
        {
            var clonedObject = new SystemState();
            clonedMap[this] = clonedObject;
            clonedObject.fieldStates = (DictionaryState<State>)fieldStates.Clone(clonedMap);
        }

        protected override string StringRepresentationInternal(Dictionary<object, string> objectPaths, string path)
        {
            return nameof(SystemState) + " " + fieldStates.StringRepresentation(objectPaths, path);
        }

        protected override void LockComponents(HashSet<object> visited)
        {
            fieldStates.Lock(visited);
        }

    }
}
